version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pastry_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/pastry_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: secret
      # etc.
    ports:
      - '3000:3000'
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '5173:5173' # Vite dev
